In [7]:
#4.1
a={'Шум1': int(input('Шум1 ')), 'Шум2': int(input('Шум2 ')) ,'Шум3': int(input('Шум3 ')), 'Шум4': int(input('Шум4 '))}
b={'не вреден для здоровья': [0,35] , 'негативное влияние на нервную систему человека':[35,70],'ухудшение слуха, головные боли':[70,85],'ухудшение слуха, головные боли':[70,85],'серьезный вред здоровью':[85,130],'– угроза жизни':[130,float('inf')]}
i=j=0
ss=[]
ak=list(a.keys())
aE=list(a.values())
bk=list(b.keys())
for ae in a.values():
    j=0
    for be in b.values():       
        if ae >= be[0] and ae < be[1]:
            ss.append(bk[j])
            s=dict(zip(ak,ss))
        j+=1
    i+=1
print(s)

Шум1 46
Шум2 89
Шум3 120
Шум4 5
{'Шум1': 'негативное влияние на нервную систему человека', 'Шум2': 'серьезный вред здоровью', 'Шум3': 'серьезный вред здоровью', 'Шум4': 'не вреден для здоровья'}


In [4]:
#4.2
import json
with  open('data.json','r') as js:
    js = json.load(js)
client={}
for i in js['events_data']:
    if i['client_id'] in client:
        client[i['client_id']] +=1
    else:
        client[i['client_id']] =1
k=0
for j in client:
    if client[j]==1:
        k+=1
print(f'одно действие совершили {k} клентов')
#print(client)




одно действие совершили 40 клентов


In [5]:
#5
import numpy as np
import random

N = int(input("Введите N: "))
M = int(input("Введите M: "))
T = random.choices(range(0, 10), k=N*M)
print(T)

A = np.array(T).reshape(N, M)
print('Исходный массив A')
print(A)

B = float(input('Введите число B: '))
C=[]
s=0
for i in T:
    if i > B:
        C.append(i)
        s+=1
print(C)
print(s)



Введите N: 3
Введите M: 3
[3, 2, 1, 2, 3, 4, 1, 0, 8]
Исходный массив A
[[3 2 1]
 [2 3 4]
 [1 0 8]]
Введите число B: 7
[8]
1


In [156]:
median=np.median(C)
print(median)

6.5


In [6]:
for i in C:
    i+=i
print(float((i+1)/len(C)))

17.0
